<?xml version="1.0"?>
<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro">

        <xacro:macro name="apartment" params="name">

	<!-- wall_00 -->
	<link name="wall_00">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${wall_depth} ${size_d+0.18+0.35} ${size_z_wall1}" />
			</geometry>
			<material name="Grey"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${wall_depth} ${size_d+0.18+0.35} ${size_z_wall1}" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="wall_00">
		<material>wall_floor_05</material>
	</gazebo>

	<joint name="joint_wall_00" type="fixed">
		<origin xyz="${-size_total_x/2+dist_axis_x-wall_depth} ${(size_total_y/2-size_d/2+0.1-dist_axis_y)+0.175} ${size_z_wall1/2}" rpy="0 0 0" />
		<parent link="dummy_link" />
		<child link="wall_00" />
	</joint>

	<!-- wall_01 -->
	<link name="wall_01">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size=" ${size_b} 0.001 0.90" />
			</geometry>
			<material name="Grey"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${size_b} 0.001 0.90" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="wall_01">
		<material>kitchen_wall_with_heating</material>
	</gazebo>

	<joint name="joint_wall_01" type="fixed">
		<origin xyz="${dist_axis_x} ${size_total_y/2-dist_axis_y+window_depth+0.02} 0.45" rpy="0 0 0" />
		<parent link="dummy_link" />
		<child link="wall_01" />
	</joint>

	<!-- wall_01_part2 -->
	<link name="wall_01_part2">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size=" ${size_b} 0.35 0.90" />
			</geometry>
			<material name="Grey"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${size_b} 0.35 0.90" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="wall_01_part2">
		<material>kitchen_window_board</material>
	</gazebo>

	<joint name="joint_wall_01_part2" type="fixed">
		<origin xyz="${dist_axis_x} ${size_total_y/2-dist_axis_y+window_depth+0.195} 0.45" rpy="0 0 0" />
		<parent link="dummy_link" />
		<child link="wall_01_part2" />
	</joint>

	<!-- wall_01_little_glas -->
	<link name="wall_01_little_glas">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.02 0.35 2.70" />
			</geometry>
			<material name="Grey"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.02 0.35 2.70" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="wall_01_little_glas">
		<material>black</material>
	</gazebo>

	<joint name="joint_wall_01_little_glas" type="fixed">
		<origin xyz="3.5 ${size_total_y/2-dist_axis_y+window_depth+0.195} 1.35" rpy="0 0 0" />
		<parent link="dummy_link" />
		<child link="wall_01_little_glas" />
	</joint>


<!-- wall_01_part3 -->
	<link name="wall_01_part3">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size=" ${size_b} ${window_depth} 1.80" />
			</geometry>
			<material name="Grey"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${size_b} ${window_depth} 1.80" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="wall_01_part3">
		<material>kitchen_wall_with_windows</material>
	</gazebo>

	<joint name="joint_wall_01_part3" type="fixed">
		<origin xyz="${dist_axis_x} ${size_total_y/2-dist_axis_y+window_depth+0.44} 1.80" rpy="0 0 0" />
		<parent link="dummy_link" />
		<child link="wall_01_part3" />
	</joint>


	<!-- wall_02 -->
	<link name="wall_02">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${wall_depth} ${size_a+0.35} ${size_z_wall2}" />
			</geometry>
			<material name="Grey"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${wall_depth} ${size_a+0.35} ${size_z_wall2}" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="wall_02">
		<material>wall_floor_05</material>
	</gazebo>

	<joint name="joint_wall_02" type="fixed">
		<origin xyz="${size_total_x/2+dist_axis_x+wall_depth} ${(size_total_y/2-size_a/2+0.15-dist_axis_y)+0.175} ${size_z_wall2/2}" rpy="0 0 0" />
		<parent link="dummy_link" />
		<child link="wall_02" />
	</joint>

	<!-- wall_03 -->
	<link name="wall_03">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size=" ${window_depth} 1.4 ${size_z_wall2}" />
			</geometry>
			<material name="Grey"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${window_depth} 1.4 ${size_z_wall2}" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="wall_03">
		<material>emergencyExit_window_left</material>
	</gazebo>

	<joint name="joint_wall_03" type="fixed">
		<origin xyz="${size_total_x/2+dist_axis_x+0.55+window_depth/2} ${0.6-dist_axis_y} ${size_z_wall2/2}" rpy="0 0 0.785398" />
		<parent link="dummy_link" />
		<child link="wall_03" />
	</joint>

	<!-- wall_04 -->
	<link name="wall_04">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${window_depth} 1.6 ${size_z_wall2}" />
			</geometry>
			<material name="Grey"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${window_depth} 1.6 ${size_z_wall2}" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="wall_04">
		<material>emergencyExit_window_right</material>
	</gazebo>

	<joint name="joint_wall_04" type="fixed">
		<origin xyz="${size_total_x/2+dist_axis_x+0.61+window_depth/2} ${-0.54-dist_axis_y} ${size_z_wall2/2}" rpy="0 0 -0.785398" />
		<parent link="dummy_link" />
		<child link="wall_04" />
	</joint>

	<!-- wall_05 -->
	<link name="wall_05">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${wall_depth} ${size_a} ${size_z_wall2}" />
			</geometry>
			<material name="Grey"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${wall_depth} ${size_a} ${size_z_wall2}" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="wall_05">
		<material>wall_floor_05</material>
	</gazebo>

	<joint name="joint_wall_05" type="fixed">
		<origin xyz="${size_total_x/2+dist_axis_x+wall_depth} ${-size_total_y/2+size_a/2-0.15-dist_axis_y} ${size_z_wall2/2}" rpy="0 0 0" />
		<parent link="dummy_link" />
		<child link="wall_05" />
	</joint>



	<!-- wall_06 
	<link name="wall_06">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size=" ${size_b} ${window_depth} ${size_z_wall2}" />
			</geometry>
			<material name="Grey"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${size_b} ${window_depth+0.02} ${size_z_wall2}" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="wall_06">
		<material>kitchen_windows</material>
	</gazebo>

	<joint name="joint_wall_06" type="fixed">
		<origin xyz="${+dist_axis_x-0.05} ${-size_total_y/2-dist_axis_y-window_depth} ${size_z_wall2/2}" rpy="0 0 0" />
		<parent link="dummy_link" />
		<child link="wall_06" />
	</joint>
-->
	<!-- wall_07 -->
	<link name="wall_07">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${wall_depth} ${size_a} ${size_z_wall1}" />
			</geometry>
			<material name="Grey"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${wall_depth} ${size_a} ${size_z_wall1}" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="wall_07">
		<material>wall_floor_05</material>
	</gazebo>

	<joint name="joint_wall_07" type="fixed">
		<origin xyz="${-size_total_x/2+dist_axis_x-wall_depth} ${-size_total_y/2+size_a/2-0.1-dist_axis_y} ${size_z_wall1/2}" rpy="0 0 0" />
		<parent link="dummy_link" />
		<child link="wall_07" />
	</joint>


	<!-- wall_08 
	<link name="wall_08">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${wall_depth} 1.9 ${size_z_wall2}" />
			</geometry>
			<material name="Grey"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${wall_depth} 1.9 ${size_z_wall2}" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="wall_08">
		<material>IPA/WallApartment</material>
	</gazebo>

	<joint name="joint_wall_08" type="fixed">
		<origin xyz="${size_total_x/2-1.8+dist_axis_x+wall_depth} ${size_total_y/2-3.3+0.1-dist_axis_y} ${size_z_wall2/2}" rpy="0 0 0" />
		<parent link="dummy_link" />
		<child link="wall_08" />
	</joint>   -->
	<!-- 3.3 = distance to wall_01 -->

<!-- wall_09 (polystyrene) -->
	<link name="wall_09">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size=" ${size_b-0.1} 0.02 ${size_z_wall2}" />
			</geometry>
			<material name="Grey"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="${size_b-0.1} 0.02 ${size_z_wall2}" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="wall_09">
		<material>polystyrene</material>
	</gazebo>

	<joint name="joint_wall_09" type="fixed">
		<origin xyz="${+dist_axis_x} -5.6 ${size_z_wall2/2}" rpy="0 0 0" />
		<parent link="dummy_link" />
		<child link="wall_09" />
	</joint>

	<!-- glas_00 -->
	<link name="glas_00">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.02 0.62 ${size_z_wall1}" />
			</geometry>
			<material name="Transparent"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.02 0.62 ${size_z_wall1}" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="glas_00">
		<material>IPA/Wall2</material>
	</gazebo>

	<joint name="joint_glas_00" type="fixed">
		<origin xyz="${-size_total_x/2+dist_axis_x-wall_depth} ${1.23-dist_axis_y-0.09} ${size_z_wall1/2}" rpy="0 0 0" />
		<parent link="dummy_link" />
		<child link="glas_00" />
	</joint>

<!-- glas_00_aluminium_part -->
	<link name="glas_00_aluminium_part">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.03 0.62 0.10" />
			</geometry>
			<material name="Transparent"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.03 0.62 0.10" />
			</geometry>
		</collision>
	</link>

	<gazebo reference="glas_00_aluminium_part">
		<material>aluminium</material>
	</gazebo>

	<joint name="joint_glas_00_aluminium_part" type="fixed">
		<origin xyz="${-size_total_x/2+dist_axis_x-wall_depth} ${1.23-dist_axis_y-0.09} 0.05" rpy="0 0 0" />
		<parent link="dummy_link" />
		<child link="glas_00_aluminium_part" />
	</joint>

	<!-- glas_01 -->
	<link name="glas_01">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.02 0.92 ${size_z_wall1}" />
			</geometry>
			<material name="Transparent"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.02 0.92 ${size_z_wall1}" />
			</geometry>
		</collision>
	</link>
	<gazebo reference="glas_01">
		<material>IPA/Wall2</material>
	</gazebo>

	<joint name="joint_glas_01" type="fixed">
		<origin xyz="${-size_total_x/2+dist_axis_x-wall_depth} ${-0.68-dist_axis_y} ${size_z_wall1/2}" rpy="0 0 0" />
		<parent link="dummy_link" />
		<child link="glas_01" />
	</joint>

<!-- glas_01_aluminium_part -->
	<link name="glas_01_aluminium_part">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.03 0.92 0.10" />
			</geometry>
			<material name="Transparent"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="0.03 0.92 0.10" />
			</geometry>
		</collision>
	</link>
	<gazebo reference="glas_01_aluminium_part">
		<material>aluminium</material>
	</gazebo>

	<joint name="joint_glas_01_aluminium_part" type="fixed">
		<origin xyz="${-size_total_x/2+dist_axis_x-wall_depth} ${-0.68-dist_axis_y} 0.05" rpy="0 0 0" />
		<parent link="dummy_link" />
		<child link="glas_01_aluminium_part" />
	</joint>

	<!-- glasdoor -->
	<link name="glasdoor">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="1.00 0.02 ${size_z_wall1}" />
			</geometry>
			<material name="Transparent"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="1.00 0.02 ${size_z_wall1}" />
			</geometry>
		</collision>
	</link>
	<gazebo reference="glasdoor">
		<material>IPA/Wall2</material>
	</gazebo>

	<joint name="glasdoor" type="fixed">
		<origin xyz="-2.63 -4.27 ${size_z_wall1/2}" rpy="0 0 0" />
		<parent link="dummy_link" />
		<child link="glasdoor" />
	</joint>

	<!-- glasdoor_aluminum_part -->
	<link name="glasdoor_aluminum_part">
		<inertial>
			<origin xyz="0 0 0" />
			<mass value="5.0" />
			<inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
		</inertial>
		<visual>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="1.00 0.03 0.10" />
			</geometry>
			<material name="Transparent"/>
		</visual>
		<collision>
			<origin xyz="0 0 0" />
			<geometry>
				<box size="1.00 0.03 0.10" />
			</geometry>
		</collision>
	</link>
	<gazebo reference="glasdoor_aluminum_part">
		<material>aluminium</material>
	</gazebo>

	<joint name="glasdoor_aluminum_part" type="fixed">
		<origin xyz="-2.63 -4.27 0.05" rpy="0 0 0" />
		<parent link="dummy_link" />
		<child link="glasdoor_aluminum_part" />
	</joint>

        </xacro:macro>
<gazebo>
	<static>true</static>
</gazebo>
</robot>
